# Generated by Django 4.2.5 on 2025-09-14 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome do estoque (ex: 'Cozinha', 'Garagem').", max_length=100, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o estoque foi criado.')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome do produto (ex: 'Arroz', 'Sabão').", max_length=200)),
                ('quantidade', models.PositiveIntegerField(help_text='Quantidade do produto em estoque.')),
                ('preco_estimado', models.DecimalField(decimal_places=2, help_text='Preço estimado do produto.', max_digits=10)),
                ('estoque', models.ForeignKey(help_text='O estoque ao qual este produto pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.estoque')),
            ],
        ),
    ]
